# Generated by Django 4.2.3 on 2023-07-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Juridica')], max_length=2),
        ),
    ]
